server:
  port: 6243
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringMvcStudy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: rootpw
    maximumPoolSize: 30
    minimumIdle: 5
    poolName: write
    readOnly: false
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: validate
      format-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: info
    org.hibernate.type.descriptor.sql: trace